name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/scripts/**'
      - '.github/workflows/build_push.yml'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          path: main
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 17
          distribution: temurin

      - name: Prepare signing key
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > main/signingkey.jks

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1

      - name: Grant execute permission for gradlew
        run: |
          chmod +x main/gradlew

      - name: Build extensions
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          MANGAPLUS_SALT: ${{ secrets.MANGAPLUS_SALT }}
        run: |
          cd main
          ./gradlew -p src assembleRelease

      - name: Clean up CI files
        run: rm main/signingkey.jks

      - name: Create repo artifacts
        run: |
          cd main
          mkdir -p repo/apk
          find src -name "*.apk" -exec mv {} repo/apk/ \;
          INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/keiyoushi/extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          java -jar ./Inspector.jar "repo/apk" "output.json" "tmp"
          python ./.github/scripts/create-repo.py

      - name: Checkout repo branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: repo
          path: repo

      - name: Commit repo
        run: |
          cd repo
          rsync -a --delete --exclude .git --exclude .gitignore --exclude repo.json ../main/repo/ .
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git status
          if [ -n "$(git status --porcelain)" ]; then
              git add .
              git commit -m "Update extensions repo"
              git push
          else
              echo "No changes to commit"
          fi
