name: Update MangaPlus App Version
on:
  schedule:
    - cron: '0 0 1,15 * *' # every 1st and 15th of the month at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install requests

      - name: Run updater
        run: python .github/scripts/update-mangaplus-appver.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/all/mangaplus
          git diff --cached --quiet || git commit -m "MangaPlus: Update `app_ver`"
          git push